name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]
    
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
    - name: CLA Assistant GitHub Actions
      if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
      uses: cla-assistant/github-action@v1.2.0-alpha
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Optional functionality to store all the blockchain signatures in the ethirium blockchain as a smart contract
        blockchain-storage-flag: false
        path-To-cladocument: 'https://github.com/Andreas-Maier/test/blob/master/cla-md'
        path-to-signatures: 'signatures/version1/cla.json'



  
